### ISSUE TITLE
Regarding cocoapods 

### ISSUE THREAD

**Issue by SURENDRA7700** [VoIPGRID/VialerSIPLib-iOS#3] opened 2016-07-27 17:42 UTC
while doing this keys.h also not visible it is missing and pods also not working ..i hope reslove this fast .i want to use this library thank you

**Comment by Joker666** [comment] 2016-07-27 17:49
Duplicate of #1 

As I mentioned keys.sample.h is there and you can already start using the library by drag and drop to your project

**Comment by m-vellinga** [comment] 2016-07-27 19:01
I'm going to close this issue as duplicate. As Joker666 stated there is a Keys.sample.h file available to use. The README.md also clarified the use of the Keys.sample.h

**Closed by m-vellinga** 2016-07-27 19:01 UTC
Labels: duplicate

**Comment by SURENDRA7700** [comment] 2016-07-28 05:52
here keys.sample .h not there in cloned project .can you please tag me compiled code successfully 
.now aliso aim working on it
